version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw d ata GW
    tables:
      - name: sales 
        identifier: raw_gz_sales
        dscription: greenweez raw data source of sales per date
      - name: product
        identifier: raw_gz_product
        description: greenweez raw data source of sales per order id
      - name: ship 
        identifier: raw_gz_ship
        description: greenweez raw data source of shipping per ship_cost






